#!/usr/bin/env bash
#
# power-profiles-daemon implementation:
# needs package power-profiles-daemon installed and the service running see here:
# https://wiki.archlinux.org/title/CPU_frequency_scaling#power-profiles-daemon
# used in i3-blocks: ~/.config/i3/i3blocks.conf together with: ~/.config/i3/scripts/power-profiles

# script to show current power profile

current_profile=$(/usr/bin/powerprofilesctl get)

print_state= "nil"

if [[ $current_profile == "power-saver" ]]; then
  print_state=""
elif [[ $current_profile == "balanced" ]]; then
  print_state=" "
elif [[ $current_profile == "performance" ]]; then
  print_state=""
fi

echo "$print_state"
